### ISSUE TITLE
How to add license key?

### ISSUE THREAD

**Issue by adiakritos** [blocknotes/activeadmin_froala_editor#1]
If I used the `as: :froala_editor` configuration within AA then I'm left to assume that I have to also pass the key as an option like so: 

      f.input :content, as: :froala_editor, input_html: { data: { key: Figaro.env.FROALA_KEY } }

Although the key does show up when I inspect the element, the license warning doesn't go away in production. 

Should I simply add a class to the text area input and then use jquery config to set this key upon initialization? At least then the key can be somewhat hidden in the minified js...

If there is some other way, please let me know.

**Comment by adiakritos** [comment]
This is the JS that is initializing the editor:

```
$(document).ready( function() {
  $('.froala-editor').each(function () {
    var options = {};
    options = $.extend({}, options, $(this).data( 'options' ));
    $(this).froalaEditor( options );
  });
});
```

Since it's grabbing a data attribute called 'options' I'm assuming that this will contain an object with keys within it. Thus I've updated my AA configs to look like this - to include the options data key:

      f.input :content, as: :froala_editor, input_html: { data: { options: { key: Figaro.env.froala_key } } }

The output is what I expect it to be.

    data-options="{"key":"<MY KEY SHOWS HERE"}"

However, pushed to production, this still doesn't work.

If I open up console and select the element manually I get my key back as expected.

    $('#page_content').data('options').key   =>  <MY KEY>

So now I should test the initializing JS without this gem, and if that doesn't work, it's not an issue with this gem.

**Comment by adiakritos** [comment]
I've added the editor without this gem and I'm still seeing the error. You can close this issue now. 

I'd suggest adding the options: { key: 'asdf' } } to the readme instructions so that others don't have to hunt through the source to figure out how to set that up.

**Comment by blocknotes** [comment]
Hi @adiakritos 
As shown in the example of the README every parameter in data options is passed to Froala:
`f.input :description, as: :froala_editor, input_html: {data: {options: {toolbarButtons: ['undo', 'redo', '|', 'bold', 'italic']}}}`
I didn't tested the "key" parameter but I don't see it in the [API options list](https://www.froala.com/wysiwyg-editor/docs/options).

**Comment by adiakritos** [comment]
> I didn't tested the "key" parameter but I don't see it in the API options list.

My point exactly. If it's not in the API options list and it's required for getting set up, you should add an instruction for it.

**Comment by blocknotes** [comment]
@adiakritos "key" is not a parameter of my plugin, in this way I should report every parameter which is not well documented. Simply every parameter is passed throught options to Froala.
By the way, thank you for the information
