### ISSUE TITLE
Is this gem unmaintained? 

### ISSUE THREAD

**Issue by arhaikal** [blocknotes/activeadmin_froala_editor#18]
Just need to know if there are plans for this gem to be updated so it will work with a newer version of active-admin. 

Thank you for the great work here.

**Comment by blocknotes** [comment]
Hey @arhaikal,
this gem is lazy-maintained 😁 

Good point BTW, I'll take care of updating it soon.

**Comment by arhaikal** [comment]
Thanks a lot, @blocknotes i would be happy to make a PR as well if you can give me a reference on how you did the updates in the past

**Comment by blocknotes** [comment]
Uhm, I saw your comment late.
I have just released a new version which update the ActiveAdmin version support ✅
