### ISSUE TITLE
Setting up the image upload with S3

### ISSUE THREAD

**Issue by siasjustin** [blocknotes/activeadmin_froala_editor#2]
Hi, this is avery neat active admin add-on. But we can not figure out how to change the upload location and configure this for S3 uploads. Do you have a working example of how this can be done with active admin froala editor and S3?

**Comment by blocknotes** [comment]
Hi @siasjustin - I didn't tested S3 upload personally, but every parameter in data options is passed to Froala:
`f.input :description, as: :froala_editor, input_html: {data: {options: {toolbarButtons: ['undo', 'redo', '|', 'bold', 'italic']}}}`
So if you know the correct Froala config it should work the same in my plugin.

**Comment by gustavoelizalde** [comment]
hey @siasjustin did you get the S3 behavior working?

@blocknotes looks like this doesn't work

`f.input :text_content, as: :froala_editor, input_html: {data: {options: {key: $FROALA_KEY, imageUploadToS3: froala_aws_upload.to_json.html_safe, toolbarButtons: [...] }}}`

froala_aws_upload is an ActiveAdmin Helper used to generate the hash needed:

```
module ActiveAdmin::ViewsHelper

  def froala_aws_upload
    options = {
      bucket: '...',
      region: 'us-east-1',
      keyStart: 'uploads',
      acl: 'public-read',
      accessKey: '...',
      secretKey: '...'
    }
    @aws_data = FroalaEditorSDK::S3.data_hash(options)
  end

end
```
The error message I get is: "_Something went wrong. Please try again_."

Followed by this console error: 

> 
OPTIONS https://undefined.amazonaws.com/undefined net::ERR_NAME_NOT_RESOLVED

Any ideas guys?

**Comment by blocknotes** [comment]
@gustavoelizalde, short answer:  can you try `froala_aws_upload.as_json` ?

Long answer - In my tests I do for example:

`f.input :description, as: :froala_editor, input_html: {data: {options: {placeholderText: 'Some text...', fileUploadToS3: {someData: 1}, toolbarButtons: ['undo', 'redo', '|', 'bold', 'italic']}}}`

In data-options of the textarea I get:

`{"placeholderText":"Some text...","fileUploadToS3":{"someData":1},"toolbarButtons":["undo","redo","|","bold","italic"]}`

And if I console.log the options passed to froalaEditor JS constructor I get:

```
fileUploadToS3: {someData: 1}
placeholderText: "Some text..."
toolbarButtons: (5) ["undo", "redo", ...
```

I think the problem is with `froala_aws_upload.to_json.html_safe` (which returns a string, not an hash) - can you try: `froala_aws_upload.as_json` ?

**Comment by chaitanya1985** [comment]
Hello @blocknotes,
**Tried following solution, but won't work for me.**

Updated active admin modal file with following line
 `f.input :description, :label => 'Description', as: :froala_editor, input_html: {data: {options: {fileUploadToS3: froala_aws_upload.as_json}}}`

Then installed following gem
`gem "froala-editor-sdk"
`

Update file initializers/active_admin.rb (added following code at end of file)
```
module ActiveAdmin::ViewHelpers
  include ViewsHelper
end
```

add helper to /helpers/active_admin/views_helpers.rb
```
module ActiveAdmin::ViewsHelper 
def froala_aws_upload
    options = {
      bucket: ENV['bucket'],
      region: 'eu-west-1',
      keyStart: 'uploads',
      acl: 'public-read',
      accessKey:  ENV['key'],
      secretKey: ENV['skew']
    }
    @aws_data = FroalaEditorSDK::S3.data_hash(options)
  end
end 
```
```
It still shows froala url for image.
ie. https://i.froala.com/download/34bf6305303910115c1bf089a98fe00e625e65fc.jpg?1532718775

**Comment by ghost** [comment]
Has this been solved? Running into the same issue here.

**Comment by mbomfim33** [comment]
Just got this to work. In our case, we were trying to send the pictures to an S3 Bucket, and we tried creating the `@aws_data` instance variable outside of the scope of the actual form. Like this: 
```
# Configuration object.
  options = {
        bucket: 'blabla',
        ...
  }

 @aws_data = FroalaEditorSDK::S3.data_hash(options)
 
  for do |f|
        ... All of the input declarations here...
        f.input :body, as: :froala_editor, label: 'Conteúdo', input_html: {data: {options: {imageUploadToS3: @aws_data.as_json }}}
  end
```

The only way we got it to actually send the hash to the frontend so it would change the image/file link, was to hash the data **inside** of the form loop: 

```
# Configuration object.
  options = {
        bucket: 'blabla',
        ...
  }
 
  for do |f|
        @aws_data = FroalaEditorSDK::S3.data_hash(options)
        ... All of the input declarations here...
        f.input :body, as: :froala_editor, label: 'Conteúdo', input_html: {data: {options: {imageUploadToS3: @aws_data.as_json }}}
  end
```

Hope this helps, and please let me know if I can clarify anything on the code above.
