### ISSUE TITLE
Not working in production

### ISSUE THREAD

**Issue by ryanhmaas** [blocknotes/activeadmin_froala_editor#3]
This works in development but not production - are there any assets that need to be precompiled?

**Comment by blocknotes** [comment]
Hi @ryanhmaas 
Can you post more informations about the problem you are encountering?
What resources paths are missing in browser Console \ Network?
What's the content of public/assets after assets clean, clobber, precompile in prod env?

**Comment by kvandake** [comment]
The product has [pricing](https://www.froala.com/wysiwyg-editor/pricing). May be this is the reason?

**Comment by blocknotes** [comment]
@kvandake it would be strange, in my opinion
If it works in development it should work the same in production.
If anyone has the same problem and can provide more informations on the error I can try to figure it out.

**Comment by oicitrapdraz** [comment]
> This works in development but not production - are there any assets that need to be precompiled?

You have to pre-compile your assets.

**Comment by blocknotes** [comment]
I agree that in these cases a manual assets pre-compile should solve the problem.
I close it.
