### ISSUE TITLE
activeadmin_froala_editor was resolved to 0.1.3, which depends on

### ISSUE THREAD

**Issue by ravindra9278** [blocknotes/activeadmin_froala_editor#7]
Bundler could not find compatible versions for gem "activeadmin":
  In snapshot (Gemfile.lock):
    activeadmin (= 2.6.0)

  In Gemfile:
    activeadmin

    activeadmin_froala_editor was resolved to 0.1.3, which depends on
      activeadmin (~> 1.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by blocknotes** [comment]
Sorry if I waited so long to update it. Done now ✅
